name: Production deploy

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy-to-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:  ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: './dist'
          install_command: yarn install
          build_command: yarn build
